# Generated by Django 5.1.3 on 2024-12-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_event_newsupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
