# Generated by Django 5.1.3 on 2024-12-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0006_company_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
