# Generated by Django 5.1.3 on 2024-12-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0008_alter_company_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
    ]
