# Generated by Django 5.1.3 on 2024-12-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0009_alter_company_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_content',
            field=models.TextField(null=True),
        ),
    ]
