# Generated by Django 5.1.3 on 2024-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0010_company_banner_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
